dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

install:
- pip install matplotlib
- pip install scipy
- pip install python-coveralls
- python setup.py install

script:
 - coverage run --source A22CERES -m pytest ./Tests

after_success: 
 - coveralls

notifications:
    email:
        recipients:
            - sai.group22.dse@gmail.com